### ISSUE TITLE
Eliminate knn code

### ISSUE THREAD

**Issue by mamoll** [flexible-collision-library/fcl#101]
The code in `include/fcl/knn` appears to be unused. Is there any reason to keep it? If not, we might as well remove it.

**Comment by sherm1** [comment]
Nearest neighbor functionality sounds useful, and I see some code that appears to be using it [like this](https://github.com/flexible-collision-library/fcl/blob/master/test/test_fcl_simple.cpp#L37). Why do you think it should go?

**Comment by mamoll** [comment]
The code that uses is simply a unit test that simply tests whether *one* of the knn data structure types works. This copied has been taken more or less directly from OMPL (which is fine), but hasn't been kept up to date with changes there. Without a clear need for it at the moment, I'd argue that less code to maintain is better. We can then also eliminate the (optional) dependency on FLANN.

**Comment by isucan** [comment]
+1 for removing
