### ISSUE TITLE
continuousCollide does not reset the ContinuousCollisionResult struct?

### ISSUE THREAD

**Issue by schmrlng** [flexible-collision-library/fcl#117]
I've noticed that running ```continuousCollide``` with the same pre-allocated ```ContinuousCollisionResult``` struct will have ```result.is_collide``` stuck on ```true``` after it is used with colliding inputs. Without diving too much into the details of the "real" implementation, it seems that at least the [code for the naive solution](https://github.com/flexible-collision-library/fcl/blob/master/src/continuous_collision.cpp#L72) doesn't make any effort to clear the results struct (i.e. set ```is_collide = false```). Is this intended behaviour?

**Comment by sherm1** [comment]
I think this is a bug. The less-naive methods do set the flag to false when there is no collision. I'll submit a fix.

**Comment by sherm1** [comment]
@schmring, please review PR #123 to see if it fixes your problem. I only changed the behavior of the naive method.

**Comment by schmrlng** [comment]
Yup, that PR looks good to me.
