### ISSUE TITLE
Cylinder-Cylinder collision wrong when tilted

### ISSUE THREAD

**Issue by guihomework** [flexible-collision-library/fcl#122]
Context:
  My Lab discovered this bug while using MoveIt! (using FCL) with the Shadow Dexterous hand, which consists of several fingers close together and with cylinders to represent collision shapes

Problem:
when moving the fingers to the side, a little, even with thiner collision cylinders that offer a large gap (more than 5mm) relatively to the fingers size, there are strange collisions as seen here.
![collision_with_primitives_small](https://cloud.githubusercontent.com/assets/6583181/14396794/f04b6de2-fdd9-11e5-8bc9-0aa395b18cee.png)

Test in MoveIt!:
to isolate the problem we created a small moveit example only with two "bars" and the problem can be reproduced. Starting from a certain angle, the collision appears. (0.13rad on both "fingers")
![j1_-0 13_j2_0 12_small](https://cloud.githubusercontent.com/assets/6583181/14397033/5460a4f4-fddb-11e5-9236-30e9f3e64f7e.png)
![j1_-0 13_j2_0 13small](https://cloud.githubusercontent.com/assets/6583181/14397036/58121f4c-fddb-11e5-9083-48645b12ed99.png)

We redid the test by changing the cylinder primitive into a mesh of exactly the same size and same number of faces as the rendered cylinders. The problem does not happen. So it must be in the primitive.

Test in FCL:
FCL has no self test for rotated cylinders, only translated if we understood well, so we decided to add a test in FCL directly that reproduces the two cylinders primitives and adds a rotation at their base (as in the hand), first of 0.12 rad and then of 0.13 rad and the test fails indeed at 0.13.

The test is available here https://github.com/guihomework/fcl/commit/b44a3aab202c260a3a1f3cceb6cd48d281769a8d

Analysis:
From the code, we think that the conversion of cylinder primitives into a hexagonal prism is the reason for the problem. Due to the small gap in between  fingers, the larger hexagonal prisms collide before their rendered counter-part "visually" collide.

Questions: 
- Can you reproduce the problem ?
- Is there a way to solve that cylinder-cylinder collision ?
- Otherwise, is there a way to augment the number of faces of the prism when cylinders are converted to meshes ?
- Or should we go for cylinder meshes directly in the model (which is then slower in other libraries like ODE used by gazebo)

thanks

**Comment by sherm1** [comment]
I think FCL needs real primitives!

**Comment by jslee02** [comment]
I haven't looked into this problem deeply, but somehow it seems the problem is gone with #154. I tested your test code [here](https://github.com/flexible-collision-library/fcl/blob/issue122/test/test_fcl_geometric_shapes.cpp#L958).

**Comment by guihomework** [comment]
thanks, will have a look if #154 also fixed my issue in the "real" world (understand not the simplified test case)

**Comment by guihomework** [comment]
@jslee02  I am so sorry to have take a year to answer. 
I just checked in our system, and I don't see the issue any longer as seen in these pictures. 

![moveit_fcl_collision_fixed_cyl-cyl_collision](https://user-images.githubusercontent.com/6583181/29424868-90d3f314-8381-11e7-8106-7a63c965a418.png)
![moveit_fcl_collision_fixed_cyl-cyl_collision2](https://user-images.githubusercontent.com/6583181/29424876-96dff7da-8381-11e7-9fde-c1a2cd910436.png)

Collisions are now ok in our hands. 

thanks. 
I close this issue.
