### ISSUE TITLE
FCL doesn't compile with octomap 1.8

### ISSUE THREAD

**Issue by anderwm** [flexible-collision-library/fcl#126]
At least because octomap::OcTreeNode has no member 'getChild'.  Here are the 1.8 release [notes](https://github.com/OctoMap/octomap/releases/tag/v1.8.0)  Octomap 1.8 is the default for ros-kinetic.

**Comment by jvgomez** [comment]
Is there any plan to solve this? I tried to do it by myself but it is not as straightforward as I thought.

**Comment by jvgomez** [comment]
PR #129 aims to solve this issue.

**Comment by jslee02** [comment]
I believe this is resolved by #129. Closing.
