### ISSUE TITLE
Import mesh from mesh created in Blender or Inventor

### ISSUE THREAD

**Issue by dblanm** [flexible-collision-library/fcl#131]
Hello everyone,

I would like to know if FC Library support importing a mesh of, i.e. a robot, to then check the collision of the link of a robot with another link.

Thank you in advance for your help.

**Comment by jf---** [comment]
hi @dblanm 

Perhaps this will give you some idea of which classes to delve into

```python
    _mesh = fcl.BVHModel()
    n_tris = len(occ_mesh_tris)
    _mesh.beginModel(n_tris, n_tris * 3)
    map(lambda x: _mesh.addTriangle(*x), occ_mesh_tris)
    _mesh.endModel()
    return fcl.CollisionObject(_mesh)
```

**Comment by dblanm** [comment]
Thank you very much for your answer, but how exactly is the mesh imported. What I want is to import a mesh from a .dae or .stl file, is it possible?

**Comment by jslee02** [comment]
From my experience, FCL doesn't provide a direct way of importing mesh files. You need to parse the vertice data from those mesh files yourself or using other libraries.

We've used [Assimp](http://www.assimp.org/) for it in our project ([example code](https://github.com/dartsim/dart/blob/master/dart/dynamics/MeshShape.cpp#L310)). Once you get the vertice data, then you could build fcl mesh as [we do](https://github.com/dartsim/dart/blob/master/dart/collision/fcl/FCLCollisionDetector.cpp#L542).

**Comment by dblanm** [comment]
Ok! Thank you for all the links!

I am not sure if I should use another thread to ask this, but I'm not sure of how the collision detection works.
I have defined an Ellipsoid Geometry with:
  CollisionGeometryPtr_t ellipsoidGeometry (new fcl::Ellipsoid(16.,16.,8.));
then I created the Transform3f elements and created several CollisionObjects:
fcl::CollisionObject link1Object (ellipsoidGeometry,tf1);
fcl::CollisionObject link2Object (ellipsoidGeometry,tf2);

After defining the collisionRequest and result,  by doing
boolean = collide(link1Object,link2Object,request,result);

Do I get if the two objects collide? Is the Ellipsoid well defined? Or do I have to set more parameters to check if the ellipsoids collide at some point?

**Comment by jslee02** [comment]
Your code looks fine to me.

The last line will return true if the two ellipsoid collides. But you should note that, by default, it will give you the binary result whether the two objects collide but not the more detailed information such as contact position, normal, penetration depth. You can get the information by adjusting the option members.

**Comment by dblanm** [comment]
In case that anyone wants another way of loading a mesh, I used a _.obj_ file implementing a loadOBJFile function within the code like this:

```c++
void loadOBJFile(const char* filename, std::vector<fcl::Vec3f>& points, std::vector<fcl::Triangle>& triangles){
  FILE* file = fopen(filename, "rb");
  if(!file)
  {
    std::cerr << "file not exist" << std::endl;
    return;
  }

  bool has_normal = false;
  bool has_texture = false;
  char line_buffer[2000];
  while(fgets(line_buffer, 2000, file))
  {
    char* first_token = strtok(line_buffer, "\r\n\t ");
    if(!first_token || first_token[0] == '#' || first_token[0] == 0)
      continue;

    switch(first_token[0])
    {
    case 'v':
      {
        if(first_token[1] == 'n')
        {
          strtok(NULL, "\t ");
          strtok(NULL, "\t ");
          strtok(NULL, "\t ");
          has_normal = true;
        }
        else if(first_token[1] == 't')
        {
          strtok(NULL, "\t ");
          strtok(NULL, "\t ");
          has_texture = true;
        }
        else
        {
          fcl::FCL_REAL x = (fcl::FCL_REAL)atof(strtok(NULL, "\t "));
          fcl::FCL_REAL y = (fcl::FCL_REAL)atof(strtok(NULL, "\t "));
          fcl::FCL_REAL z = (fcl::FCL_REAL)atof(strtok(NULL, "\t "));
          fcl::Vec3f p(x, y, z);
          points.push_back(p);
        }
      }
      break;
    case 'f':
      {
        fcl::Triangle tri;
        char* data[30];
        int n = 0;
        while((data[n] = strtok(NULL, "\t \r\n")) != NULL)
        {
          if(strlen(data[n]))
            n++;
        }

        for(int t = 0; t < (n - 2); ++t)
        {
          if((!has_texture) && (!has_normal))
          {
            tri[0] = atoi(data[0]) - 1;
            tri[1] = atoi(data[1]) - 1;
            tri[2] = atoi(data[2]) - 1;
          }
          else
          {
            const char *v1;
            for(int i = 0; i < 3; i++)
            {
              // vertex ID
              if(i == 0)
                v1 = data[0];
              else
                v1 = data[t + i];

              tri[i] = atoi(v1) - 1;
            }
          }
          triangles.push_back(tri);
        }
      }
    }
}
}
```
I close the issue.
