### ISSUE TITLE
Debugging error

### ISSUE THREAD

**Issue by dblanm** [flexible-collision-library/fcl#133]
I am trying to debug a code using:

```cpp
#include <fcl/distance.h>
#include <fcl/math/transform.h>
#include <fcl/collision.h>
#include <fcl/collision_object.h>
#include <fcl/shape/geometric_shapes.h>
int main(){
  typedef std::shared_ptr<fcl::CollisionGeometry>CollisionGeometryPtr_t;
// Define a Ellipsoid with the dimensions needed
  //This geometry may be modified depending on the robot
  CollisionGeometryPtr_t boxGeometry (new fcl::Box(16.,16.,8.));
}
```

And it gives me the following errors
```
/usr/local/include/fcl/collision_object.h:64: undefined reference to 'fcl::AABB::AABB()'
/usr/local/include/fcl/shape/geometric_shapes.h:79: undefined reference to 'vtable for fcl::Box'
```

My Cmake looks like this:
```cmake
cmake_minimum_required(VERSION 2.8)

project(testcoll)

add_executable(testcoll main.cpp)

install(TARGETS testcoll RUNTIME DESTINATION bin)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")

include_directories (/usr/local/include/eigen2)

if (FCL_HAVE_OCTOMAP)
  add_fcl_test(test_fcl_octomap test_fcl_octomap.cpp test_fcl_utility.cpp)
endif()
```
What am I missing?

**Comment by jslee02** [comment]
I would try with:
```cmake
cmake_minimum_required(VERSION 2.8)

project(testcoll)

find_package(FCL REQUIRED)

add_executable(testcoll main.cpp)
target_link_libraries(testcoll ${FCL_LIBRARIES})

#...
```

Also, it would be nicer if you use [code highlighting](https://help.github.com/articles/creating-and-highlighting-code-blocks/) for your posts.

**Comment by dblanm** [comment]
Thank you I didn't know how to highlight the code.
I tried to add the find_package, and the code looks like this:
```cmake
cmake_minimum_required(VERSION 2.8)

project(testcoll)

find_package(FCL REQUIRED)

add_executable(testcoll main.cpp)
target_link_libraries(testcoll ${FCL_LIBRARIES})

#...
```
But it gives me the following error 
```
  Could not find a package configuration file provided by "fcl" with any of
  the following names:

    fclConfig.cmake
    fcl-config.cmake

  Add the installation prefix of "fcl" to CMAKE_PREFIX_PATH or set "fcl_DIR"
  to a directory containing one of the above files.  If "fcl" provides a
  separate development package or SDK, be sure it has been installed.
```
When I installed fcl I didn't set the DCMAKE variable, so I thought that could be the reason, I installed fcl again by doing this time:
_cmake -DCMAKE_PREFIX_PATH=/home/user/fcl-master/build .._

But the error persists, and I have been able to find the Configs files in 
_/usr/local/lib/x86_64-linux-gnu/cmake/fcl/_

Could you tell me what is missing in the cmake? Thanks!

**Comment by jslee02** [comment]
Have you installed fcl using the `install` target? The whole command to build and install fcl would be something like:
```
$ mkdir build
$ cd build
$ cmake ..
$ make
$ sudo make install
```

**Comment by dblanm** [comment]
Yes, should I remove fcl and try to install it again?

**Comment by jslee02** [comment]
Oh, wait, I forgot that fcl only provides `fcl.pc` but not `FCLConfig.cmake`. You could use `PkgConfig`, but I prefer using `FindXXX.cmake` way:

1. Copy [`FindFCL.cmake`](https://github.com/dartsim/dart/blob/master/cmake/FindFCL.cmake) to `your/project/folder/cmake`

1. Modify your main `CMakeLists.txt` as:

```cmake
cmake_minimum_required(VERSION 2.8)

project(testcoll)

set(CMAKE_MODULE_PATH "${CMAKE_SOURCE_DIR}/cmake")

find_package(FCL REQUIRED)

add_executable(testcoll main.cpp)
target_link_libraries(testcoll ${FCL_LIBRARIES})

#...
```

This should work.

**Comment by dblanm** [comment]
Where is FindFCL.cmake file? I've searched in 
```
/local/include/fcl
/usr/local/lib/x86_64-linux-gnu/cmake/fcl
fcl-master branch
```
 and could't find it.

**Comment by jslee02** [comment]
It's not installed your system. You should write one yourself, but you could find one we wrote for our project from the link in the above comment. Here is [the link](https://github.com/dartsim/dart/blob/master/cmake/FindFCL.cmake) again.

**Comment by dblanm** [comment]
It worked! Thank you very much for all the support!

**Comment by traversaro** [comment]
For completeness: the current `default` branch of `fcl` actually provides/installs a fclConfig.cmake file, the only problem is that it only exports the imported target `fcl` but no old style `FCL_LIBRARIES` variable. 

This should then work fine even without writing any custom `FindFCL.cmake` :  
~~~
cmake_minimum_required(VERSION 2.8)

project(testcoll)

find_package(fcl REQUIRED)

add_executable(testcoll main.cpp)
target_link_libraries(testcoll fcl)

#...
~~~

This was introduced in https://github.com/flexible-collision-library/fcl/pull/116 .

**Comment by jslee02** [comment]
Thank for the correction @traversaro !

**Comment by hjamal3** [comment]
In the new FCL your header files have all moved around, so be careful there.
