### ISSUE TITLE
Multiple contact points for primitive shapes

### ISSUE THREAD

**Issue by jslee02** [flexible-collision-library/fcl#15]
I'm Jeongseok Lee a member of DART development team. DART is powered by FCL for rigid body collision detection. We are trying to fully utilize FCL.

DART is using meshes for primitive shapes and now we want to use FCL's primitive shapes to reduce the computational cost and get analytical contact results. We however have an issue that FCL returns only one contact point for primitive shape collision which is a critical to us. 

In some cases, multiple contact points are necessary in dynamics simulation. For example, when we lay a box on the ground (let's assume that the ground is thin box shape), we need at least three contact points to support the box. With one contact point at the center of the box's bottom face, it is unstable and can be fall down through the ground.

FCL gets contact point from GJKSolver_indep::shapeIntersect() or GJKSolver_libccd::shapeIntersect(). The shapeIntersect() function calls boxBoxIntersect() and boxBoxIntersect() gets multiple contact points from boxBox2() but returns the average of the contact points. (see: narrowphase.cpp ln:1350)

~~~cpp
bool boxBoxIntersect(const Box& s1, const Transform3f& tf1,
                     const Box& s2, const Transform3f& tf2,
                     Vec3f* contact_points, FCL_REAL* penetration_depth_, Vec3f* normal_)
{
  std::vector<ContactPoint> contacts;
  int return_code; 
  Vec3f normal;
  FCL_REAL depth;
  /* int cnum = */ boxBox2(s1.side, tf1.getRotation(), tf1.getTranslation(),
                           s2.side, tf2.getRotation(), tf2.getTranslation(),
                           normal, &depth, &return_code,
                           4, contacts);

  if(normal_) *normal_ = normal;
  if(penetration_depth_) *penetration_depth_ = depth;

  if(contact_points)
  {
    Vec3f contact_point;
    for(size_t i = 0; i < contacts.size(); ++i)
    {
      contact_point += contacts[i].point;
    }

    contact_point = contact_point / (FCL_REAL)contacts.size();

    *contact_points = contact_point;
  }

  return return_code != 0;
}
~~~

It may not easy to decide which set of contact points is correct depend on colliding primitive shape combinations. However, it would be nice if FCL returns multiple contact points and the user enable to select contact points what the user wants. 

Please let me know if I'm misunderstanding about FCL, thanks!

**Comment by hsu** [comment]
Looks like a very useful API update for simulation. @isucan, could this go into next FCL release?
@jslee02 has some work to PR here.

**Comment by isucan** [comment]
I agree, this would be a great change to have. I would happily merge such a PR.

**Comment by jslee02** [comment]
Pull request #47 was created for this issue.

**Comment by mxgrey** [comment]
It looks like @jslee02 finished [a pull request](https://github.com/flexible-collision-library/fcl/pull/52) that's relevant for this issue, but I suppose the PR might not have been enough to make the cylinder primitive work as we need it to.

I don't see any open issues on FCL about getting multiple contact points for the cylinder, so maybe it would be a good idea for us to open one?

I'm guessing the main issue here is that the math for computing multiple contact points will be fairly challenging to work out, especially since primitives tend to have a volume of contact, so there's an important question of: How do you select a discrete set of points from that volume?.
