### ISSUE TITLE
Test fcl_geometric_shapes fails in different architectures

### ISSUE THREAD

**Issue by j-rivero** [flexible-collision-library/fcl#170]
Although the `fcl_geometric_shapes` test passes in amd64 it is [failing in a good variety of architectures](https://buildd.debian.org/status/logs.php?pkg=fcl&ver=0.5.0-1), including [i386](https://buildd.debian.org/status/fetch.php?pkg=fcl&arch=i386&ver=0.5.0-1&stamp=1471364099). This was [reported by Debian](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=834561).

```
 2/14 Test  #3: test_fcl_geometric_shapes .........***Failed    0.36 sec
Running 51 test cases...
11.102 17.885
/«PKGBUILDDIR»/test/test_fcl_geometric_shapes.cpp(409): error: in "shapeIntersection_spherecapsule": check res == expected_res has failed [false != true]
/«PKGBUILDDIR»/test/test_fcl_geometric_shapes.cpp(425): error: in "shapeIntersection_spherecapsule": check res == expected_res has failed [false != true]
/«PKGBUILDDIR»/test/test_fcl_geometric_shapes.cpp(237): error: in "shapeIntersection_spherecapsule": check sameNumContacts has failed
```

I've created a [testing job](http://build.osrfoundation.org/job/fcl-pkg_builder-master-ubuntu_xenial-i386/3/consoleFull#console-section-2) to demostrate the failures on Trusty i386. The testing job includes a Dockerfile (copy/paste) that can be used to work on debugging locally.

Let me know if you need more help to reproduce it.

**Comment by jslee02** [comment]
My hunch is [this](https://github.com/flexible-collision-library/fcl/commit/9200965b4641af419aacc536f1791fbfb59da1c0#diff-9e2bb53ae1f3a1e17bbb55818a2a62c1R994) where the change was made after FCL 0.5. However, I'm not sure how to ensure if it fixes the problem since FCL 0.5 passes all the CI tests (Travis CI and Appveyor).

**Comment by jslee02** [comment]
Wait, it was not. After I looked into the build log of your testing job, it seems [this](https://github.com/flexible-collision-library/fcl/blame/master/test/test_fcl_geometric_shapes.cpp#L884) should fix the problem.

How can I rerun your testing job with the fix?

**Comment by j-rivero** [comment]
Not present in latest versions, thanks! https://buildd.debian.org/status/package.php?p=fcl&suite=experimental
