### ISSUE TITLE
Unresolved external symbols when using FCL

### ISSUE THREAD

**Issue by arzezniczak** [flexible-collision-library/fcl#173]
Hello.
I'm trying to use FCL library in project. I've build Release x86 version of FCL lib without any errors, but when I try to use it I'm getting this errors:
`1>X.obj : error LNK2001: unresolved external symbol _ccdFirstDirDefault`
`1>X.obj : error LNK2001: unresolved external symbol _ccdMPRIntersect`
`1>X.obj : error LNK2001: unresolved external symbol _ccdMPRPenetratio`

Any idea how to get rid of these errors?

**Comment by jslee02** [comment]
It seems `libccd`, which is a dependency of FCL, is not linked to your project. It should be automatically linked if you use CMake build system (recommended) to use FCL as:
```cmake
find_package(fcl)
include_directories(${fcl_INCLUDE_DIRS})
target_link_libraries(your_project_name ${fcl_LIBRARIES})  # linking fcl and its dependencies
```
You could link `libccd` manually, but I would suggest using CMake.

**Comment by arzezniczak** [comment]
I am using CMake (gui version). First I'm building Eigen, then libccd, then I'm building FCL and setting in Cmake includes (Eigen and libccd) and lib (libccd only since Eigen is include only). I'm skipping octomap.
As a generator I'm using Visual Studio 2015.

**Comment by jslee02** [comment]
Could you post the `CMakeLists.txt` of your project? Also, please make sure all the dependencies are corrected found using `REQUIRED` option (e.g., `find_package(fcl REQUIRED)`).

**Comment by arzezniczak** [comment]
I'm not familiar with CMake build system and I'm not sure if I good understand you :smiley: 
In my project I'm not using CMake, I'm using it only to build Visual Studio solution of FCL, libccd and Eigen libraries.
But I guess you wan't to see if I set properly usage of libccd library in my project (?) I can show you this in Visual Studio project properties window.
This is in linker settings:
![image](https://cloud.githubusercontent.com/assets/20474251/18351509/bc918b34-75da-11e6-88a9-a7458f2f72e8.png)
And this is in C/C++ settings:
![image](https://cloud.githubusercontent.com/assets/20474251/18351526/ce1e1e9e-75da-11e6-8812-dc4b4ac70ddc.png)
Of course files are present in this selected paths.

**Comment by jslee02** [comment]
You could use CMake to generate Visual Studio solution, but it's up to you.

It seems you set only include/lib directories, but not library files. If I'm correct you can set them at Linker/Input in the project setting dialog in VS.

**Comment by arzezniczak** [comment]
Yeah, thank you!
It works now.
