### ISSUE TITLE
traversal node setup

### ISSUE THREAD

**Issue by dblanm** [flexible-collision-library/fcl#176]
Since the last release of **FCL 0.6.0** the _traversal_node_setup.h_ has disappeared, which included the _traversal_node_octree_ between others. 
I cannot find anything related to the exact updates done by the 0.6.0 release. 
Could anyone tell me which one is the similar header to _traversal_node_setup.h_? Since **OMPLapp** relies upon this header.

Thanks in advance!

Edit: using FCL 0.5.0 (while compiling OMPLapp) gives the following error

``` c++
/usr/local/include/fcl/octree.h: In member function ‘fcl::OcTree::OcTreeNode* fcl::OcTree::getNodeChild(fcl::OcTree::OcTreeNode*, unsigned int)’:
/usr/local/include/fcl/octree.h:200:18: error: ‘fcl::OcTree::OcTreeNode’ has no member named ‘getChild’
     return node->getChild(childIdx);
                  ^
/usr/local/include/fcl/octree.h: In member function ‘const OcTreeNode* fcl::OcTree::getNodeChild(const OcTreeNode*, unsigned int) const’:
/usr/local/include/fcl/octree.h:210:18: error: ‘const OcTreeNode’ has no member named ‘getChild’
     return node->getChild(childIdx);
```

Does FCL still not support octomap 1.8.0? The compilation of FCL with octomap worked using #142

**Comment by jslee02** [comment]
You could use `fcl.h` that will be installed at the top level of the include directory. It includes all the necessary FCL headers so that you no longer need to try to figure out which FCL headers should be included for your use.

FCL should support octomap 1.8.0 with #126 and #129, but I'll take a look at it.
