### ISSUE TITLE
Unresolved external symbol ___ccdSupport

### ISSUE THREAD

**Issue by arzezniczak** [flexible-collision-library/fcl#183]
I have problem with compilation (code is from master brach pulled yesterday).
I can't compile few tests - every one of them is using `__ccdGJK` function.
Specific linker error:
`8>fcl.lib(gjk_libccd.obj) : error LNK2019: unresolved external symbol ___ccdSupport referenced in function "int __cdecl fcl::detail::libccd_extension::__ccdGJK(void const *,void const *,struct _ccd_t const *,struct _ccd_simplex_t *)" (?__ccdGJK@libccd_extension@detail@fcl@@YAHPBX0PBU_ccd_t@@PAU_ccd_simplex_t@@@Z)
8>fcl.lib(gjk_libccd.obj) : error LNK2001: unresolved external symbol _ccd_vec3_origin`

I've done some small research and it looks like in fact there is declaration in `narrowphase\detail\convexity_based_algorithm\support.h` but no definition.

**Comment by jslee02** [comment]
How did you compile the tests? The definition is in `libccd` so it should work if you link to `libccd` correctly.

**Comment by arzezniczak** [comment]
I was trying now to ignore the test, but still I have the same errors when building library only without tests.
I'm using Visual Studio 2015, default solution configuration Debug Win32.
I think I have correctly linked libccd. By default i see it's added in additional include directories and in additional dependencies, it's not added in additional library directories but even if I try to add there libccd\lib folder - it's still not working.
Last time (about month ago) I was building FCL and there was no problem - I was doing exactly the same things, using default configs in CMake - but now it's not working properly.

**Comment by jslee02** [comment]
Great! Thanks for sharing this. I'd like to leave this issue open until we have the patches like what you did.

**Comment by xendian** [comment]
I have also similar issue..fcl.lib is generated without any problem. But whenever I try to build the test_fcl_collision or any test projects, I am getting linker errors as the following;

1>------ Build started: Project: test_fcl_collision, Configuration: Debug x64 ------
1>fcl.lib(gjk_libccd.obj) : error LNK2019: unresolved external symbol __ccdSupport referenced in function "int __cdecl fcl::detail::libccd_extension::__ccdGJK(void const *,void const *,struct _ccd_t const *,struct _ccd_simplex_t *)" (?__ccdGJK@libccd_extension@detail@fcl@@YAHPEBX0PEBU_ccd_t@@PEAU_ccd_simplex_t@@@Z)
1>fcl.lib(gjk_libccd.obj) : error LNK2001: unresolved external symbol ccd_vec3_origin
.......   \test\Debug\test_fcl_collision.exe : fatal error LNK1120: 2 unresolved externals


I've checked the libccd, and ccd_vec3_origin is already defined as extern like the following;

extern ccd_vec3_t *ccd_vec3_origin;



Does anybody have an  idea on the problem?

**Comment by arzezniczak** [comment]
Errors are exactly the same as in my case.
Did you try to resolve them the same way as I explained?

**Comment by xendian** [comment]
I solved the problem;
All the errors are coming from libccd dependency. The libccd does not export(at least the version I have) the  
**void __ccdSupport(const void *obj1, const void *obj2, const ccd_vec3_t *dir, const ccd_t *ccd, ccd_support_t *supp);**

and **ccd_vec3_origin** variable  

What you need to do is to export this function and the variable. So put **_ccd_export** before the definitions such as;

**_ccd_export extern ccd_vec3_t *ccd_vec3_origin;**
**_ccd_export void __ccdSupport(const void *obj1, const void *obj2,
                  const ccd_vec3_t *dir, const ccd_t *ccd,
                  ccd_support_t *supp);**

**Comment by xendian** [comment]
I think if this solves your problem as well, we could close the  issue

**Comment by jslee02** [comment]
If this is a problem of `libccd`, it would be great someone report this to the upstream.

**Comment by jslee02** [comment]
Is this related to [this](https://github.com/danfis/libccd/pull/29/files)?

**Comment by arzezniczak** [comment]
Yup, I've posted this issue [here](https://github.com/danfis/libccd/issues/26) and it looks like this should resolve this issue in FCL too.

**Comment by talregev** [comment]
engine_collision_convex.c.obj : error LNK2001: unresolved external symbol _ccd_vec3_origin.
It seems that libccd is not active.

**Comment by SeanCurtis-TRI** [comment]
@talregev It seems that your issue is a mujoco issue. Can you confirm that it's using the most current version of libccd? As this is not an fcl issue (`engine_collision_convex.c` is not a part of FCL), I'm going to go ahead and close this issue.

**Comment by talregev** [comment]
I can confirm that I compile mujoco with vcpkg and we use ccd with double-precision and it solve the issue.
