### ISSUE TITLE
lots of compilation errors

### ISSUE THREAD

**Issue by xendian** [flexible-collision-library/fcl#184]
I am using visual studio 20113 and getting lots of errors on ;
Error   10  error C2146: syntax error : missing ';' before identifier 'S'  in  ....\fcl-master\src\broadphase\broadphase_collision_manager.cpp

due to in .....\fcl-master\include\fcl\math\constants.h line number 49

I am gettin 591 errors due to this.. Any body has the same issue?

**Comment by sherm1** [comment]
I believe you need VS 2015 to compile successfully.

**Comment by xendian** [comment]
Thanks!!.I will try..it seems visual 2013 compiler has a problem with  the constexpr

**Comment by xendian** [comment]
yes, visual studio 2015 solved the issues.
