### ISSUE TITLE
Error: template argument required for 'class AABB'

### ISSUE THREAD

**Issue by ytzhao** [flexible-collision-library/fcl#186]
Hi, 
I'm using FCL for manipulator collision check, this library is very new to me. I followed the instructions to install this library on Ubuntu16.04 without ROS. I used 'general_test.cpp' for testing in Codeblocks with following build message:
'error: template argument required for 'class AABB''.

I've already included the library path and .h files in the project. I had several tries and found that if I commented <fcl/shape/geometric_shapes.h>, <fcl/shape/geometric_shapes_utility.h>, <fcl/narrowphase/narrowphase.h> these three files, there's no compiling error. 

Once I included either of these three header files, the compiling error appears. I traced down into these files and found that there are two AABB.h files in the library. One is <fcl/BV/AABB.h> and another is <fcl/math/bv/AABB.h>. The later file is written with 'template<typename S>' while the former one is not. It seems that if the former file is included, there's always the same error. So what's the different use between these two files? Is the one with template the newest version?

Anyone have ideas for solving this problem?

Thanks! :-)

**Comment by jslee02** [comment]
`general_test.cpp` hasn't been updated for the new API (FCL 0.6). It was an oversight. I'll create a PR that updates the test.

The templated one is the newest version. I guess the non-templated one is the old version that's installed in the system directory.

**Comment by ytzhao** [comment]
Thank you! Anyway, I reinstalled this library with more stable version 0.5, OpenRAVE and OMPL depend on the former version.
