### ISSUE TITLE
Help needed

### ISSUE THREAD

**Issue by xendian** [flexible-collision-library/fcl#192]
Can anyone suggest an example code/documentation for the API for two 3D convex mesh collision (with GJK) with fcl?..we would need penetration depth and direction 

Thanks!.

**Comment by SeanCurtis-TRI** [comment]
Given the long duration between unanswered question and now, I'm assuming that the issue has already been resolved by the user or is no longer relevant. If I'm mistaken, feel free to open the issue back up.
