### ISSUE TITLE
Minor documentation typo

### ISSUE THREAD

**Issue by ljmanso** [flexible-collision-library/fcl#22]
Line 50 of README.md:
typedef BVHModel<OBBRSS>* Model;

should be:
typedef BVHModel<OBBRSS> Model;

**Comment by jslee02** [comment]
I think it should be either
```cpp
typedef BVHModel<OBBRSS> Model;
Model* model = new Model();
```
or
```cpp
typedef BVHModel<OBBRSS>* Model;
Model model = new Model();
```

I guess the author meant the first one by typedef'ing OBBRSS model as the default model.
