### ISSUE TITLE
Inconsistent interpretations of capsule origin

### ISSUE THREAD

**Issue by avalenzu** [flexible-collision-library/fcl#225]
Where is the origin of an `fcl::Capsule` geometry? [Lines 62 - 65](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/geometry/shape/capsule-inl.h#L62) of [`capsule-inl.h`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/geometry/shape/capsule-inl.h) appear to indicate that the origin is at the center of the line segment that defines the capsule:

```c++
  const Vector3<S> v_delta(radius, radius, 0.5 * lz + radius);
  this->aabb_local.max_ = v_delta;
  this->aabb_local.min_ = -v_delta;
```
[`sphere_capsule-inl.h`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/primitive_shape_algorithm/sphere_capsule-inl.h) also considers the origin of the capsule to be at the center of the line segment.

However, [line 151](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/primitive_shape_algorithm/capsule_capsule-inl.h#L151) and following in [`capsule_capsule-inl.h`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/primitive_shape_algorithm/capsule_capsule-inl.h) appear to indicate that the origin is at one of the end-points of the line segment:

```c++
  Vector3<S> p1(tf1.translation());
  Vector3<S> p2(tf2.translation());

  // line segment composes two points. First point is given by the origin, second point is computed by the origin transformed along z.
  // extension along z-axis means transformation with identity matrix and translation vector z pos
  Transform3<S> transformQ1 = tf1 * Translation3<S>(Vector3<S>(0,0,s1.lz));
  Vector3<S> q1 = transformQ1.translation();

  Transform3<S> transformQ2 = tf2 * Translation3<S>(Vector3<S>(0,0,s2.lz));
  Vector3<S> q2 = transformQ2.translation();
```
Is there something I'm missing here? Or are the two files actually inconsistent? If so, I'm happy to modify `capsule_capsule-inl.h` to use the same convention as the other files (origin at the center of the line segment).

**Comment by avalenzu** [comment]
@jslee02, I'm assigning this to you to confirm that I'm not crazy. Please re-assign to me if you agree that this is an actual bug.

**Comment by jslee02** [comment]
I also believe they are not inconsistent; `capsule_capsule-inl.h` needs to be fixed.

Re-assigning to you as I see it's an actual bug. :smile:
