### ISSUE TITLE
Eigen type vectors need to use Eigen aligned allocator

### ISSUE THREAD

**Issue by woodychow** [flexible-collision-library/fcl#249]
All vectors that contain Eigen type should use Eigen::aligned_allocator
http://eigen.tuxfamily.org/dox-devel/group__TopicStlContainers.html

For example
```
-int BVHModel<BV>::addSubModel(const std::vector<Vector3<S>>& ps)
+int BVHModel<BV>::addSubModel(const std::vector<Vector3<S>, Eigen::aligned_allocator<Vector3<S>>>& ps)
```

Am I missing something? I can fix all usages of Eigen vectors like this. If you have something else in mind, could you please let me know?

**Comment by curds01** [comment]
It's worth noting that this *particular* example doesn't seem to apply. the documentation you linked to states:

> These issues arise only with fixed-size vectorizable Eigen types and structures having such Eigen objects as member. For other Eigen types, such as Vector3f or MatrixXd, no special care is needed when using STL containers.

If you follow the link to the [fixed-sized vectorizable](http://eigen.tuxfamily.org/dox-devel/group__TopicFixedSizeVectorizable.html) objects, `Vector3` is not included. 

So, now it is my turn to ask, "Am I missing something?"

**Comment by woodychow** [comment]
Oh sorry. I didn't realize Vector3 is not one of the fixed sized vectorizables. Thank you very much.
