### ISSUE TITLE
broken unit tests

### ISSUE THREAD

**Issue by mamoll** [flexible-collision-library/fcl#25]
in 0.3.0 the following two unit tests are broken: test_fcl_broadphase and test_fcl_shape_mesh_consistency. In the first one there might some sort of memory corruption.

**Comment by jslee02** [comment]
**test_fcl_broadphase** and **test_fcl_shape_mesh_consistency** seems to work now but [other 4 tests are failing](https://travis-ci.org/dartsim/fcl/jobs/53141229#L882). As a side note, **test_fcl_simple** doesn't work on only debug mode.

**Comment by jslee02** [comment]
The current master branch passes all the unit tests so I believe this issue is addressed. Please reopen if it's not.
