### ISSUE TITLE
Master/0.6 should be bumped to 1.0 since it introduces breaking changes.

### ISSUE THREAD

**Issue by SlightlyCyborg** [flexible-collision-library/fcl#254]
The header file structure was changed in 0.6, which means it should be bumped to 1.0 at least.

Compiling dart with the master of fcl is not possible, and now I am wondering if I should use 0.3, 0.4, or 0.5.

**Comment by jslee02** [comment]
I believe 0.x (0 major version) doesn't guarantee API compatibility until it becomes 1.0.0 or greater. Please report to DART repo if you have any DART issues.
