### ISSUE TITLE
Mac release failures -- box-box intersection

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [flexible-collision-library/fcl#265]
PR #259 introduced code that is apparently failing in CI. It specifically fails in mac release builds. Across *all* tests, no collisions are being reported.

**Comment by sherm1** [comment]
@mamoll reported this in #271:
> Unit tests pass on my Mac, OS X 10.13.3, Xcode 9.2, Boost 1.66 and libccd 2.0 (the last two installed via MacPorts).

**Comment by ericberberich** [comment]
I have seen `test_fcl_capsule_box_1` here on Xcode 9.x - it's the gjksolver instantiated with libccd that produces the wrong result .... the TravisCI for Linux uses `libccd 1.5` - so I downgraded to it - but it still appears ... I will have another look into it - any idea which direction to search?

**Comment by mamoll** [comment]
Note that MacPorts installs libccd with double precision by default (`-DCCD_DOUBLE=true`). Maybe TravisCI has libccd with single precision installed and that's what's causing the failure?

**Comment by jslee02** [comment]
FYI, [Travis CI installs `libccd` using Homebrew](https://github.com/flexible-collision-library/fcl/blob/master/ci/install_osx.sh#L6), and [Homebrew installs `libccd` with double precision by default](https://github.com/Homebrew/homebrew-core/blame/master/Formula/libccd.rb#L18).

**Comment by geoynomous** [comment]
So `libccd` is always with double precision in all your TravisCI setups?

**Comment by SeanCurtis-TRI** [comment]
This is no longer true. A modicum of archaeology was insufficient to point to the exact solution. So, I'm giving up on that. CI passes; 'nuff said.
