### ISSUE TITLE
Vector3 setIdentity

### ISSUE THREAD

**Issue by geoynomous** [flexible-collision-library/fcl#272]
Eigen's _setIdentity_ on Vector3 creates (1,0,0)^T - see the output of this code

```C++
  Vector3<S> v;
  std::cout << "v1 " << v << std::endl;
  v.setIdentity();
  std::cout << "v2 " << v << std::endl;
  v.setZero();
  std::cout << "v3 " << v << std::endl;
```

> v1 0
> 0
> 0
> v2 1
> 0
> 0
> v3 0
> 0
> 0
> 

I grepped through the code and it seems to not be used - but maybe someone can cross-check. It's just very counter-intuitive (on Vector, though Eigen sees it as a 3x1 matrix)

**Comment by jmirabel** [comment]
I guess you are mixing `setIdentity` and `setOnes`. `setIdentity` refers to the identity element of the NxN matrix product operation. A space of non-square matrices is not a group so there is no identity matrix.

**Comment by geoynomous** [comment]
@jmirabel thanks for the reply ... no that I got. I was more concerned that Eigen allows to `setIdentity` on the non-square Matrix (aka a Vector here). The confusion was wrt to the _neutral_ element of the vectors: There is `setZero` for the neutral element of addition. But it seems that Eigen does not model that ... anyhow - it's more a side remark.
