### ISSUE TITLE
Solver tolerances do *not* scale with scalar precision

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [flexible-collision-library/fcl#278]
Problem
=======
The solvers [`GJKSolver_libccd`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/gjk_solver_libccd-inl.h#L905) and [`GJKSolver_indep`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/narrowphase/detail/gjk_solver_indep-inl.h#L951) use tolerances for the GJK and EPA algorithms to determine when the iterative algorithm should stop. These tolerances are hard-coded to a simple 1e-6 (see links above). This is an artifact from the former 32-bit floating point days. 

The default values *should* depend on the underlying scalar type.

Proposal
=======
Extend [`fcl::constants`](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/math/constants.h#L46) to provide some convenient, precision-dependent tolerance values and use those scalar-dependent functions to default initialize the solver values.

**Comment by sherm1** [comment]
:+1:

Quick survey: are people still using FCL in float precision?
