### ISSUE TITLE
Mac CI using single-precision libccd

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [flexible-collision-library/fcl#291]
It appears that the mac ci is using single-precision libccd.

#290 failed the new unit tests. Instead of getting solutions to a tolerance of 1e-14, it was getting results satisfied to within 1e-7. Furthermore, when evaluating the tests on a local mac with known double-precision libccd, these errors did not appear. But when forcing it to use single-precision libccd, the errors appeared.

**Comment by SeanCurtis-TRI** [comment]
This needs a refresh.

The [homebrew formula now specifically refers to libccd v2.1](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libccd.rb#L4).

However, between libccd v2.0 to v2.1, the CMake mechanism for specifying double precision changed from the macro [`CCD_ENABLE` in 2.0](https://github.com/danfis/libccd/blob/v2.0/CMakeLists.txt#L20) to [`ENABLE_DOUBLE_PRECISION` in 2.1](https://github.com/danfis/libccd/blob/v2.1/CMakeLists.txt#L25). However, the formula still uses the [2.0 spelling](https://github.com/Homebrew/homebrew-core/blob/master/Formula/libccd.rb#L17).

So, it seems we've reversed our old problem where, originally, we were pulling v2.0 but using the v2.1 spelling. Now we're using v 2.1 but using the v2.0 spelling.

I'm not a mac user, so I'd ask for one of the previous supporters of mac to help out on this one. If no one volunteers to do so, I'll step in. @scpeters @jslee02?

**Comment by jslee02** [comment]
PR is submitted: https://github.com/Homebrew/homebrew-core/pull/37365

**Comment by mamoll** [comment]
It doesn't make a difference in the 2.1 release. Both ways of specifying precision are supported:
https://github.com/danfis/libccd/blob/v2.1/src/CMakeLists.txt#L1-L17
Still, not a bad idea to switch to the new preferred way before the old way is deprecated.

**Comment by SeanCurtis-TRI** [comment]
Given that with that observation and all of the discussion in the homebrew pr, we can safely close this issue.

(Feel free to re-open this if you feel I've been overly optimistic.)
