### ISSUE TITLE
When will there be a new release of master?

### ISSUE THREAD

**Issue by v4hn** [flexible-collision-library/fcl#331]
Hi everyone, in particular @jslee02 @sherm1 @SeanCurtis-TRI, I guess.

I guess I ask this in the general interest of the ROS/MoveIt community.

There were *lots* of contributions to the library (many labeled "fixes"),
that are currently in upstream `master` but not released.
The last published release is 0.3.4 - a backport release @jslee02 did last year.
0.5.0 was released over two years ago.

In ROS kinetic there are unofficial custom snapshots via https://github.com/wxmerkt/fcl_catkin ,
but even they are not up to date anymore.

Ubuntu 18.04 (and thus ROS melodic) at the moment use 0.5.0 (https://packages.ubuntu.com/bionic/libfcl-dev),
which is older than the snapshots mentioned above.

There has been quite a bit of discussion on problems with FCL and possible advantages of the Bullet checker in MoveIt lately and outdated code probably makes things worse.

What's the situation?
Does it not make sense to do a new release because you broke the whole API and it's not settled yet?
Do you miss the developers to do a release?
Did performance only decrease since 0.5.0 and you struggle to improve on it again?

**Comment by SeanCurtis-TRI** [comment]
Some excellent questions. And, while not immediately obvious, this is tangentially related to #329. One of the things we'd discussed vis a vis #329 was releasing a new version for some of the reasons you've outlined above. You've just provided even more reasons above and beyond those already considered. So, bumping FCL seems like the right thing to do.

**Comment by v4hn** [comment]
I'm very happy to hear that! :+1:

With all the discussion points in #329, please keep in mind that

- the core of a release is only a tag in the git and the resulting tarball.
  Everything else is a very much appreciated bonus, but please don't leave releases pending long just because you cannot take care of the overhead of releasing it into 5 different packaging systems right away.
  If people want the software in some system, someone will take care of it eventually.

- Looking at the pretty deep under-the-hood changes you discuss, I think it would be a good idea to do a release *before* you start doing them :)

Thank you so much for your work in this project everyone!

**Comment by wxmerkt** [comment]
@v4hn There is a newer working version which includes the latest fcl-master ([here](https://github.com/ipab-slmc/fcl_catkin/commit/c5382bfffb13cc09823d9627bcf2fd29e4028658)), however, not yet released to the ROS build farm (I am traveling at the moment and plan to release it to the buildfarm this weekend or early next week).

I do agree and support a new release before #323/#329 (as in https://github.com/flexible-collision-library/fcl/issues/323#issuecomment-416526505).

**Comment by v4hn** [comment]
Here is the pull-request, mentioned above, to adapt MoveIt for the new FCL API for reference:
https://github.com/ros-planning/moveit/pull/1156

At the moment we plan to wait for your release before we merge the request.
You forced us to use the new API functions for compatibility with FCL 0.5 and 0.6
and it would be nice to depend on officially released API in MoveIt's official code base.

**Comment by v4hn** [comment]
another friendly ping. We are still waiting for a release.

**Comment by sherm1** [comment]
There is a release-candidate tag now: https://github.com/flexible-collision-library/fcl/releases/tag/0.6.0RC

**Comment by scpeters** [comment]
@j-rivero @SeanCurtis-TRI let's discuss here a 0.6 release

**Comment by SeanCurtis-TRI** [comment]
Let's get the official timeline for getting this into Ubuntu 20. And we'll look at the issues that we were hoping to resolve prior to moving from RC to final release.

**Comment by j-rivero** [comment]
The end of Debian imports for the next Ubuntu happens at the end of February. I would need some time to prepare the new upload and handle the library transition (libfcl0.5 to 0.6). This involves the participation of other Debian developers. Does February 10th works for you as death line to release 0.6?

**Comment by SeanCurtis-TRI** [comment]
If Feb 10 is the line we need to work with to make sure you can do your job and we can address any issues that come up, then so be it. Let's go ahead and draw that line.

We'll independently figure out if we can meet it.  :)

**Comment by SeanCurtis-TRI** [comment]
@j-rivero I think we'll be good for targeting Feb 10th.

I just want to make sure I understand the division of labor so that we don't miss anything. I infer from your message that if we get the repo in a "good' state, you'll be handling preparing the Debian package and all of those fun and games? Or have I misunderstood that?

Ideally, if you could enumerate exactly what you need from us by the 10th, I can make sure it's done.

**Comment by j-rivero** [comment]
> Ideally, if you could enumerate exactly what you need from us by the 10th, I can make sure it's done.

Sure. In Debian we usually work with stable releases from upstream project. Anything that you (as upstream project) consider a stable release should be enough for me to work on packaging and having the corresponding mechanisms in place in order to be compliance with Debian/Ubuntu policies.

**Comment by scpeters** [comment]
and to be more explicit, I think @j-rivero would like @SeanCurtis-TRI to make a release using the GitHub web UI, which will create a tag?

**Comment by j-rivero** [comment]
> and to be more explicit, I think @j-rivero would like @SeanCurtis-TRI to make a release using the GitHub web UI, which will create a tag?

Not strictly necessary for me but I think that is the current way of creating fcl releases so makes total sense to me yes.

**Comment by jwnimmer-tri** [comment]
> Ideally, if you could enumerate exactly what you need from us by the 10th, I can make sure it's done.

@SeanCurtis-TRI another toward due dates -- ideally, prior to tagging a release here, all of the changes would be fully vetted by both Drake CI and TRI's internal CI.  Those extra tests might isolate some failures that FCL's own suite would miss.  That probably needs a day or two of extra soak time where all release-targeted FCL commits are merged, prior to the 10th.

**Comment by SeanCurtis-TRI** [comment]
That was exactly my idea as well.  :)

**Comment by SeanCurtis-TRI** [comment]
@j-rivero I believe we're ready to go. Release [0.6.0](https://github.com/flexible-collision-library/fcl/releases/tag/v0.6.0) has been through its own CIs, Drake's CI, and our internal project's CI. So, I'm going to pass the baton to you  -- let me know if you encounter anything that requires further attention.

**Comment by arocchi** [comment]
@v4hn @wxmerkt FYI

**Comment by scpeters** [comment]
updating homebrew formula: https://github.com/Homebrew/homebrew-core/pull/49975

**Comment by wxmerkt** [comment]
Thank you all for the great effort in pushing this forward :-). I will make a new release of fcl_catkin to Kinetic/Melodic once the CI goes green for it.

**Comment by SeanCurtis-TRI** [comment]
@j-rivero How is this going? A couple of things have come up recently which may want us to shift to 0.6.1 as the Ubuntu release. Is that possible?

(#450 and #452)

**Comment by j-rivero** [comment]
> @j-rivero How is this going? A couple of things have come up recently which may want us to shift to 0.6.1 as the Ubuntu release. Is that possible?

The upload is still being reviewed by Debian developers, not sure if we will get in on time. In the good news part, yes, we can send a 0.6.1 as the new version. Create the new release in github a will upload it.

**Comment by SeanCurtis-TRI** [comment]
@j-rivero For what it's worth, there's a 0.6.1 available.

**Comment by v4hn** [comment]
Thanks again for the release. You forgot to close the issue.
