### ISSUE TITLE
Tag for 0.6.0 and Updated readme

### ISSUE THREAD

**Issue by kumar-akshay324** [flexible-collision-library/fcl#343]
Though the documentation available [here](https://flexible-collision-library.github.io/) is for FCL version 0.6.0, I don't see a tagged version in the source. I believe it the master branch touted as 0.6.0, isn't it? 

For someone who is using standardized versions and creating dependencies out of that, it would be very helpful to create a new ASAP because the file structure and import headers have all been changed from 0.5.0 to 0.6.0 (the master branch!).

Recent commits on the **master** like Eigen transform mode change from AffineCompant to Isometry changes a lot fo things and the **readme** does not reflect it.

Do these suggestions sound reasonable?

**Comment by SeanCurtis-TRI** [comment]
A very popular topic the last month or so: #329 (and then *it* links to others). I think it's largely a case of figuring out if there are any stray threads that are in flight that we want in 0.6.0 and then pulling the trigger.

**Comment by kumar-akshay324** [comment]
Yes, agreed. But until then, atleast the readme and the documentation should be updated to reflect the changes or it kills the purpose of using the master branch. 

I should be hopeful of a tagged 0.6.0 soon. Thanks.

**Comment by SeanCurtis-TRI** [comment]
At least recently, PRs have been pushed toward updating the [change log](https://github.com/flexible-collision-library/fcl/blob/master/CHANGELOG.md). I don't know how far back that goes and it might require some exploration to make it more comprehensive prior to 0.6.0. But there's *some* progress in that regard.
