### ISSUE TITLE
Make C++ error - unrecognized '-msse' - ubuntu 16.04

### ISSUE THREAD

**Issue by jakecza** [flexible-collision-library/fcl#351]
Not sure where I'm going wrong here, compiled all dependencies and followed all steps with no problems until running make within the **build** directory right after **cmake ..**

Output:
```
[  1%] Building CXX object src/CMakeFiles/fcl.dir/broadphase/broadphase_dynamic_AABB_tree_array.cpp.o
c++: error: unrecognized command line option ‘-mfpmath=sse’
c++: error: unrecognized command line option ‘-msse’
c++: error: unrecognized command line option ‘-msse2’
c++: error: unrecognized command line option ‘-msse3’
c++: error: unrecognized command line option ‘-mssse3’
src/CMakeFiles/fcl.dir/build.make:62: recipe for target 'src/CMakeFiles/fcl.dir/broadphase/broadphase_dynamic_AABB_tree_array.cpp.o' failed
make[2]: *** [src/CMakeFiles/fcl.dir/broadphase/broadphase_dynamic_AABB_tree_array.cpp.o] Error 1
CMakeFiles/Makefile2:181: recipe for target 'src/CMakeFiles/fcl.dir/all' failed
make[1]: *** [src/CMakeFiles/fcl.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by SeanCurtis-TRI** [comment]
What compiler are you running?

**Comment by jamiesnape** [comment]
Also what architecture?

There is a bug here regardless (not all compilers that masquerade as GNU support the flags we add for all architectures), which is fixed somewhere in my long chain of future PRs.

**Comment by jakecza** [comment]
g++11 & Ubuntu 16.04. My computer is a Lenovo yoga 920 w/ Intel Core i7-8550U x64-bit

**Comment by jamiesnape** [comment]
My understanding was that the latest (development) version of GCC, and hence `g++` was 9. Could you clarify "g++11"?

**Comment by jamiesnape** [comment]
Also please rerun with `cmake -DCMAKE_VERBOSE_MAKEFILE=ON` and paste the raw compiler command that is echoed prior to the error.

**Comment by jdawahare** [comment]
I have received the same error as @jakecza. I am running ubuntu 18.04 on a jetson Xavier (CPU: 8-core NVIDIA Carmel 64-bit ARMv8.2 @ 2265MHz) 

the output of `cmake -DCMAKE_VERBOSE_MAKEFILE=ON`  
```
-- Set RPATH explicitly to '/usr/local/lib'
-- FCL uses OctoMap
-- Configuring done
-- Generating done
-- Build files have been written to: /media/jay/sataDrive/fcl/build
```

**Comment by jamiesnape** [comment]
`-msse` is not going to be supported on ARM. You need `cmake -DFCL_USE_X64_SSE=OFF`, which, to be honest, probably should be the default.

**Comment by jdawahare** [comment]
@jamiesnape you the sunshine on a cloudy day, thank you!
