### ISSUE TITLE
fcl/traversal/traversal_node_octree.h not found

### ISSUE THREAD

**Issue by abhileshborode** [flexible-collision-library/fcl#356]
Hey ,

I recently tried to build this package:
https://github.com/ayushgaud/path_planning

when I try to build it I receive this FCL related error 
 fatal error: fcl/traversal/traversal_node_octree.h: No such file or directory
compilation terminated.

I tried to locate traversal_node_octree.h header file in the FCL include directory and it was no where to be found. 

Was this file removed from the latest FCL release ? or has it been renamed to some other header file ?

Please let me know...

Thanks

**Comment by abhileshborode** [comment]
I found  fcl/traversal/traversal_node_octree.h in the branch: fcl-0.5 release. I guess the current master branch removed it.

**Comment by EricWang1hitsz** [comment]
> I found fcl/traversal/traversal_node_octree.h in the branch: fcl-0.5 release. I guess the current master branch removed it.

hello, I met the similar problem when I build the "path_planning" packages: fcl: octree.h: No such file or directory.

Do you know how to solve the problem? I cam find the .h file in /usr/local/include
