### ISSUE TITLE
compilation error in test file

### ISSUE THREAD

**Issue by doudou** [flexible-collision-library/fcl#372]
~~~
fcl/test/narrowphase/detail/convexity_based_algorithm/test_gjk_libccd-inl_gjk_doSimplex2.cpp:181:67: note:   deduced conflicting types for parameter ‘_Tp’ (‘double’ and ‘float’)
     const ccd_real_t eps = std::max({1., p_OA.norm(), p_OB.norm()}) * kEps;
~~~

Changing the `1.` to `1.0f` does fix the error, but I'm guessing that the double/float error might be a configuration thing (maybe ?).

**Comment by sherm1** [comment]
Whoops! Should be `T(1)` (where T is the template argument) to avoid committing to float or double prematurely (assuming we're still supporting float precision).

This suggests that CI doesn't include `float` tests?

**Comment by SeanCurtis-TRI** [comment]
Actually, in this case, it should be `ccd_real_t(1)`. This test isn't expressed in terms of `T`, but in terms of `ccd_real_t`. And, clearly, this test is running against a float-based libccd. I'll patch the test.

**Comment by SeanCurtis-TRI** [comment]
The PR for this is in. I've confirmed the reported compilation error and that this fixes it (on my machine). @doudou, if you'd like to confirm as well, that'd be appreciated. Otherwise, we'll just go straight through PR review and merge it.

**Comment by doudou** [comment]
@SeanCurtis-TRI yep, #373 does the trick
