### ISSUE TITLE
Collision check for line joining two 3D points

### ISSUE THREAD

**Issue by indraneelpatil** [flexible-collision-library/fcl#376]
Hi there!

I am currently working on a custom motion planner around obstacles modelled as the fcl::octree datatype. I want to trace a line between two distinct 3D points and check if the line is in collision with any part of the octomap of the environment.
Currently I have tried alligning a cylindrical fcl::CollisionModel along the line joining the two points and then iteratively check whether this cylinder is safe or not using this 
 
```
fcl::OcTree* tree2 = new fcl::OcTree(std::shared_ptr<const octomap::OcTree>(octTree));
 std::vector<fcl::CollisionObject*> boxes;
 generateBoxesFromOctomap(boxes, *tree2);
std::shared_ptr<Cylinder> Cylinder1(new Cylinder(0.03,magnitude));  //radius,length of collision object
 CollisionObject co1(Cylinder1, tf1);
fcl::collide(&co1, box, request, result);
```

But I am sure there must be an easier way to check if the line is safe or not. I have found the classes fcl::InterpMotion and fcl::InterpolationLinear but I have no idea how to use them or whether they are useful in this context.

Any guidance on how to check for the collision of the line joining two points against an octomap is highly appreciated!

Thanks in advance,
Indraneel.

**Comment by SeanCurtis-TRI** [comment]
This is going to be one of those answers that may only be partially helpful.

The problem you're describing is closely related to continuous collision detection (I.e., you have a vertex position at time t and t + delta and want to know if there was a collision along the linearly-interpolated position in that time interval). I believe FCL has a continuous collision detection collection API and I *suspect* you can use it for this purpose.

**Comment by indraneelpatil** [comment]
@SeanCurtis-TRI  Thank you for your time. That is an excellent idea. I would love to try this out and then post the link to my code here. 
The example implementation for this is already given on their ReadME page -
[https://github.com/flexible-collision-library/fcl](url)

In the meanwhile I am closing this issue. Thanks again for your help!
