### ISSUE TITLE
FCL compilation error with ros

### ISSUE THREAD

**Issue by aswinthomas** [flexible-collision-library/fcl#39]
Hi all,
I have the following error. All I did was do find_package(FCL REQUIRED) in my CMakeLists.txt.

CMake Error at /opt/ros/hydro/share/fcl/fcl-config.cmake:103 (message):
  Project 'fcl' specifies 'include' as an include dir, which is not found.
  It does not exist in 'include'.  Ask the maintainer 'Ioan Sucan
  <isucan@willowgarage.com>' to fix it.

Any ideas how to fix this?

Regards
Aswin

**Comment by jslee02** [comment]
Closing this issue since it hasn't been updated for a long time. Please reopen this if this is still an issue.
