### ISSUE TITLE
Current pkg config restricts the c++ standard as `c++11` for all downstream users

### ISSUE THREAD

**Issue by yszheda** [flexible-collision-library/fcl#404]
Currently, `pkg-config --cflags fcl` will use `--std=c++11` as one of the compilation flags for the downstream users. It's defined in https://github.com/flexible-collision-library/fcl/blob/master/fcl.pc.in#L12

```
Cflags: @PKG_CFLAGS@ -I${includedir}
```

And `PKG_CFLAGS` is set in https://github.com/flexible-collision-library/fcl/blob/master/CMakeLists.txt#L279

```
if(NOT MSVC)
    set(PKG_CFLAGS "-std=c++11")
endif()
```

However, for downstream users who wants to use features from more recent C++ standards ( e.g. `-std=c++14` / `-std=c++17` ), the `-std=c++11` flag specified by `pkg-config --cflags fcl` will lead to compilation failure.

**Comment by traversaro** [comment]
Unfortunately, this is a known problem related to how `pkg-config` is used to export information on the C++ standard using raw compilers flags instead of some kind of metadata that can be interpreted by build systems that consume the pkg-config configuration files, see https://mwoehlke.github.io/cps/history.html#what-s-wrong-with-pkg-config for a related discussion.

Probably the easiest solution is to sanitize in your build system the flags provided by fcl's pkg-config. Which build system are you using for your project?

**Comment by yszheda** [comment]
Hi @traversaro , thank you for the kind reply.

> Probably the easiest solution is to sanitize in your build system the flags provided by fcl's pkg-config. Which build system are you using for your project?

Currently our team use autotools as our build system, and we have worked around the problem by post-processing the `pkg-config --cflags` results and deleting `-std=c++11`.
But I'm still confused why we have to set raw compiler flags like `-std=c++11` in the `Cflags` of the `.pc` file? If we intend to force downstream users to compile their code with `-std=c++11`, how to make sure those users who don't use `pkg-config` also use this specified flag? (Actually I can't see any clues from the CMake files that we have managed to do so) Otherwise, the downstream users have to remove `-std=c++11` manually, then what's the point of setting this `Cflag` in the `.pc` file?

**Comment by sherm1** [comment]
Any thoughts on how this ought to be addressed @jamiesnape or @j-rivero ?

**Comment by jamiesnape** [comment]
The last specified of any mutually exclusive `-std` options on the common compilers takes effect, so you don't usually even have to sanitize the flags in most cases. I don't think this is something we can fix. Obviously, using CMake is preferred.

**Comment by yszheda** [comment]
Thanks! Since the problem is not supposed to be fixed in this repo, I will close this issue.
