### ISSUE TITLE
Could FCL use GPUs?

### ISSUE THREAD

**Issue by davetcoleman** [flexible-collision-library/fcl#405]
Hi all,

I just searched the issue history and code for any reference to "GPU" and there is nothing relevant to indicate FCL could compute on a GPU. Has anyone looking into adding this or have plans for this? Seems like it could offer big speed ups for projects like MoveIt.

I see in the original FCL publication that GPUs were left for Future Work. I also caught wind many years ago that maybe GPU support was almost added in the original development by @panjia1983 but then held back for commercial reasons. I'd love to know more about this :-)

Thanks!

**Comment by mamoll** [comment]
Maybe this is what you're thinking of?:

http://gamma.cs.unc.edu/gplanner/

and

Jia Pan, Dinesh Manocha, GPU-based parallel collision detection for fast motion planning, IJRR 31(2):187-200, 2011.
https://doi.org/10.1177/0278364911429335

I have asked Dinesh Manocha a long time ago about whether there were any plans to release it, but my memory of that discussion was the code was still very much "research code" and not quite ready for release. If it *has* been commercially released, that would be nice to know.

**Comment by davetcoleman** [comment]
Thanks for the quick response @mamoll. This answers my question.

**Comment by hazidh** [comment]
Is there any code example currently available that supports the use of GPU to accelerate the efficiency of collision detection?
