### ISSUE TITLE
Segfault when calling DynamicAABBTreeCollisionManager::registerObjects with empty vector

### ISSUE THREAD

**Issue by Zera-** [flexible-collision-library/fcl#41]
I am trying to integrate FCL into an existing scenegraph-system, that internally manages multiple levels of object-grouping. In order to use the broadphase algorithms of FCL I fill instances of fcl::DynamicAABBTreeCollisionManager for each grouping.

During the creation of a higher-level grouping I then attempt to add the list of collision objects in the subgroup that is currently empty.

The manager starts a tree traversal for insertion, and the final insertion method HierarchyTree<BV>::topdown_0(in file include/fcl/broadphase/hierarchy_tree.hxx, line 353) then tries to touch the first element of the empty list(line 386), causing a segfault.

The method topdown_0 even checks the number of elements before doing the main processing, so I assume it could be a reasonable place to catch the special case of an empty list. However, I can't really assess the affects of setting the root pointer of the tree to NULL (as would be my natural answer to no insertion).

I suspect that similar cases are also currently unhandled by the library, making the usage quite unrelieable.

If you could set a guideline on when special cases should be caught (As early as possible? Or process them until they have to be handled?), I'd be up to fixing issues I find myself and submitting pull requests.

**Comment by jslee02** [comment]
A pull request #64 was created to solve this issue.

**Comment by jslee02** [comment]
I believe this issue is fixed by #64.
