### ISSUE TITLE
Test test_gjk_libccd-inl_epa.cpp does not compile on Windows due to non-portable M_PI

### ISSUE THREAD

**Issue by traversaro** [flexible-collision-library/fcl#448]
Similar to https://github.com/flexible-collision-library/fcl/pull/264, probably this went undetected due to ~~https://github.com/flexible-collision-library/fcl/issues/442~~, https://github.com/flexible-collision-library/fcl/issues/389 .

Error log:
~~~
2020-02-23T14:59:10.6836579Z D:\a\drake-lite-cmake\drake-lite-cmake\fcl\test\narrowphase\detail\convexity_based_algorithm\test_gjk_libccd-inl_epa.cpp(260,48): error C2065: 'M_PI': undeclared identifier [D:\a\drake-lite-cmake\drake-lite-cmake\fcl\build\test\narrowphase\detail\convexity_based_algorithm\test_gjk_libccd-inl_epa.vcxproj]
~~~

**Comment by SeanCurtis-TRI** [comment]
And yet, the tests passes CI. Thoughts?

**Comment by traversaro** [comment]
> And yet, the tests passes CI. Thoughts?

I think the problem is that the test requires octomap, that is not included in the CI as discussed in https://github.com/flexible-collision-library/fcl/issues/442 .

**Comment by SeanCurtis-TRI** [comment]
That test requires octomap? That is deeply surprising. My first instinct would be to say that is an error. Can you point to the artifact that suggests the test depends on octomap and I'll investigate further?

**Comment by traversaro** [comment]
Sorry, I got confused. The relevant issue is https://github.com/flexible-collision-library/fcl/issues/389. In particular, due to the old  `ccd` used, `ccd` is not available  as an imported target, and so the check `if(TARGET ccd)` in https://github.com/flexible-collision-library/fcl/blob/master/test/narrowphase/detail/convexity_based_algorithm/CMakeLists.txt#L12 fails.
