### ISSUE TITLE
Missing find_dependency call in fclConfig.cmake when imported targets are used in target_link_libraries

### ISSUE THREAD

**Issue by traversaro** [flexible-collision-library/fcl#449]
In the CMake build scripts of `fcl`, if the imported targets  `Eigen3::Eigen`, `ccd` or `octomap` are defined, they are used in `target_link_libraries` with `PUBLIC` visibility (see https://github.com/flexible-collision-library/fcl/pull/196). When this  happens, then in the `fclConfig.cmake` script the appropriate [`find_dependency`](https://cmake.org/cmake/help/v3.12/module/CMakeFindDependencyMacro.html) script should be added, to ensure that the imported  targets are properly defined also in the downstream project that consume `fcl` via `find_package(fcl)`.

**Comment by jamiesnape** [comment]
Would people complain if we stopped supporting the spaghetti of different ways of finding all these packages? Does anyone actually know what the minimum supported versions of all three are?

**Comment by traversaro** [comment]
> Would people complain if we stopped supporting the spaghetti of different ways of finding all these packages? Does anyone actually know what the minimum supported versions of all three are? 

I would definitely in favor of doing so. However, unfortunately the situation regarding ccd is a bit messy, especially if you want to support also the version installed by debian repositories. In particular, the version currently in Debian sid is the latest 2.1, but it does not contain the ccd-config.cmake file (fyi @j-rivero), probably as it has been generated using the autotools-based build systems.

**Comment by jamiesnape** [comment]
Looks like eigen and octomap have the necessary CMake files back to Xenial, even, so unless anyone complains, I will simplify those while I fix this. Looks like for CCD, I need to support pkg-config.

**Comment by jamiesnape** [comment]
Actually CI is on Trusty, so I guess that is a complaint. I will just fix as is, for now, since I am assuming this will be in a patch release.
