### ISSUE TITLE
Improve efficiency by collision detection between BVs and set level of BV tree

### ISSUE THREAD

**Issue by hph73** [flexible-collision-library/fcl#465]
Hi, 

I have successfully installed fcl and I am able to run collision detection by following the instructions. However, according to my testing, it takes up to 2 seconds to test collision between two binary STL meshes of size around 25 MB. This is too slow for my application and I am trying to find a way to accelerate the process.

Here are two specific requirements for my application. 
(1) I only care about whether collision occurs or not. So, I already set the following parameters.
 int num_max_contacts = 1;
 bool enable_contact = false;
(2) I even don't care whether two objects are really colliding or not. Can I only test collision between the boundary volumes (BVs) of the two objects so that I can get collision results faster? And how to control the level of the BV tree of the two objects so that I can adjust the parameter to hit a balance between speed and accuracy.

Thanks!

Hao

**Comment by SeanCurtis-TRI** [comment]
Bad news:

`int num_max_contacts = 1` doesn't do what you hope . That's a parameter that hopes to (possibly) give multiple points *per* contacting geometry pair.

Good news:
You *can* make this cheaper. You have to provide a callback function for the broadphase. That callback can tell the broadphase to stop (by returning `true`). Just make sure your callback has enough state (stored in the data provided as `callback_data` to know that you've encountered one leaf and you're gold.

**Comment by hph73** [comment]
> 
> 
> Bad news:
> 
> `int num_max_contacts = 1` doesn't do what you hope . That's a parameter that hopes to (possibly) give multiple points _per_ contacting geometry pair.
> 
> Good news:
> You _can_ make this cheaper. You have to provide a callback function for the broadphase. That callback can tell the broadphase to stop (by returning `true`). Just make sure your callback has enough state (stored in the data provided as `callback_data` to know that you've encountered one leaf and you're gold.

Hi SeanCurtis-TRI,

Thanks for your quick reply. I am new to fcl. Do you know where I can find resources/examples about customizing the callback function for the broadphase? I noticed that there are quite a few examples in the test folder. Which one do you think work best for this purpose?

Thanks,

Hao

**Comment by SeanCurtis-TRI** [comment]
If you look at the last section of the [README.md](https://github.com/flexible-collision-library/fcl/blob/master/README.md) file, it shows collision between two "broadphase managers". The call I would point your attention towards is:

`manager2->collide(manager1, &collision_data, DefaultCollisionFunction);`.

We're going to modify that in the following way. We're going to provide a novel callback function and some data.

```c++
bool simple_callback(fcl::CollisionObject*, 
                     fcl::CollisionObjectd*, 
                     void* callback_data) {
  // We ignore the actual objects and assume if the broadphase could not cull the two
  // objects, we'll consider that evidence of contact.

  // We expect that this callback is only ever invoked where the callback_data is
  // simply a pointer to a bool.
  bool* collision_found = static_cast<bool*>(callback_data);
  // Indicate that broadphase found a candidate object pair.
  *collision_found = true;
  // This tells the broadphase to stop working.
  return true;
}

...
bool collision_found = true;
// Swap the DefaultCollisionData and DefaultCollisionFunction for our simplified versions.
manager2->collide(manager1, &collision_found, simple_callback);
if (collision_found) {
  std::cout << "Broad phase found at least one candidate pair!\n";
}
```

**Comment by hph73** [comment]
Hi SeanCurtis-TRI,

Thanks for your detailed answer. My another questions is how to control the level of the BV tree. I noticed that I can control the initial tree level by setting `tree_init_level` but how to control the maximum level of the bv tree?

Thanks!

Hao

**Comment by SeanCurtis-TRI** [comment]
There's not much you could or should do to worry about the tree level. It's a binary tree and the depth comes down to how many leaves you have and how well balanced and full the tree is. That's really the responsibility of the BVH algorithm.

**Comment by jmirabel** [comment]
Why don't you simplify your meshes instead ?
