### ISSUE TITLE
Distance function not behaving as expected

### ISSUE THREAD

**Issue by jlack1987** [flexible-collision-library/fcl#480]
I have a branched chain model involving a relatively large number of collision objects and i'm trying to compute if a given object is in collision with any other object. I'm using the `DynamicAABBTreeCollisionManager` and am seeing different behaviors depending on which `distance` API call I use. If I use,

```
/// @brief perform distance test for the objects belonging to the manager (i.e., N^2 self distance)
  void distance(void* cdata, DistanceCallBack callback) const;

```

The result I get is correct I believe and returns correct values; however, if I use,

```
/// @brief perform distance computation between one object and all the objects belonging to the manager
  void distance(CollisionObject* obj, void* cdata, DistanceCallBack callback) const;
```

it doesn't seem to be checking `obj` against all of the other links and is returning an incorrect result. Note that for this call, `obj` does belong to the collision manager from which the `distance` call is being made. I don't see any documentation that indicates this should cause an issue. 

To test this in both cases the callabck that I provide prints out the names of all the collision objects that are checked. In the case of it checking distances for all objects belonging to the manager I see it checking everything, but with the other it only checks a small subset of all of the collision objects. Hopefully this is sufficient info for the issue i'm having to be understood.

**Comment by SeanCurtis-TRI** [comment]
Thanks for the post. Let me see if I understand this properly.

- The first API you referenced `void distance(void* cdata, DistanceCallBack callback) const` is this one: https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/broadphase/broadphase_dynamic_AABB_tree.h#L108-L109.
- The second API you referenced `void distance(CollisionObject* obj, void* cdata, DistanceCallBack callback) const` is this one: https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/broadphase/broadphase_dynamic_AABB_tree.h#L102-L103
- In your distance callback, you are logging all geometry pairs that are provided as inputs.
  - in the *first* API, you are logging all N² pairs.
  - in the *second* API, where you are providing a single geometry *from the tree*, you are not registering N-1 pairs.

Did I get that right?

**Comment by SeanCurtis-TRI** [comment]
Quick question: does your distance callback change the input parameter `dist` (as shown [here](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/broadphase/broadphase_collision_manager.h#L57-L60)).

If you write to that value, you'll end up culling potential pairs.

**Comment by SeanCurtis-TRI** [comment]
(And your callback is always returning `false`?

**Comment by jlack1987** [comment]
Ok in trying to get a bare bones example for you I have found that I was mismanaging my return value in the distance callback, so it's a bug on my end and after fixing it it behaves as expected. Really appreciate your quick response though and sorry to have wasted a bit of your time. I'll close
