### ISSUE TITLE
collision area

### ISSUE THREAD

**Issue by ZhouY1129** [flexible-collision-library/fcl#484]
Can the FCL library calculate the collision area?

**Comment by SeanCurtis-TRI** [comment]
I'm afraid not. It's only attempt at characterizing collision is a sense of "depth" of penetration.

**Comment by ZhouY1129** [comment]
Thank you very much for your answers。

**Comment by ZhouY1129** [comment]
Can the FCL library determine the collision relationship between multiple objects in space?
