### ISSUE TITLE
Collision relationship between multiple objects in space

### ISSUE THREAD

**Issue by ZhouY1129** [flexible-collision-library/fcl#487]
Can the FCL library determine the collision relationship between multiple objects in space?

**Comment by jmirabel** [comment]
What do you mean by relationship ?

**Comment by SeanCurtis-TRI** [comment]
@ZhouY1129 It's been a week or so. The issue, as is, isn't actionable. I'm closing the issue for now. If you want to revisit it and can offer elaboration on the original topic, feel free to re-open and clarify.
