### ISSUE TITLE
Move from Trusty (Ubuntu 14) to Bionic (Ubuntu 18)

### ISSUE THREAD

**Issue by SeanCurtis-TRI** [flexible-collision-library/fcl#490]
Ubuntu 14 is no longer supported. However, [CI is configured to be running on Trusty](https://github.com/flexible-collision-library/fcl/blob/master/.travis.yml#L2). This is antiquated and will only cause maintenance headaches. I propose we move supported Ubuntu version to Bionic (Ubuntu 18) (knowing that Ubuntu 20 is just around the corner).

A preliminary foray has been made in #489, changing the CI configuration and patching whatever needs patching to make it compatible with the native compilers in Bionic.

This is your chance to vote on why we shouldn't do this (or offer your uncondtional support for this being a welcome, if over-delayed move). I'm going to let this issue set for two weeks to collect feedback. Without compelling arguments against this move, on Aug 25, 2020 we'll pull the trigger and move to Bionic.

Let the comments commence.

**Comment by sherm1** [comment]
Count me in favor of a move to Ubuntu 18.04!

**Comment by SeanCurtis-TRI** [comment]
Well, it's been two weeks and no one is complaining. 

Also, it appears that our antiquated mac CI configuration (xcode 9) is [also causing problems](https://github.com/flexible-collision-library/fcl/pull/488#issuecomment-680221911). So, we'll bump that up to alleviate those issues as well. Assuming that #489 is happy and friendly, we'll go ahead and merge it.
