### ISSUE TITLE
New release tag

### ISSUE THREAD

**Issue by wxmerkt** [flexible-collision-library/fcl#532]
There have been [26 commits to master since 0.6.1](https://github.com/flexible-collision-library/fcl/compare/0.6.1...master) has been released a year ago including many bug fixes to algorithms. Would you consider creating a patch release for 0.6.x? Or is there a plan for an upcoming release?

Many thanks,
Wolfgang

**Comment by scpeters** [comment]
the changes in https://github.com/flexible-collision-library/fcl/pull/467 look like API changes, so I would expect the next release to be 0.7.0, rather than 0.6.2

**Comment by scpeters** [comment]
https://github.com/flexible-collision-library/fcl/releases/tag/0.7.0
