### ISSUE TITLE
Document how to work with the dual release to Noetic

### ISSUE THREAD

**Issue by peci1** [flexible-collision-library/fcl#533]
On Ubuntu Focal with ROS Noetic, there are two installs of libfcl. One system from `libfcl-dev`, and one ROS from `ros-noetic-fcl`.

I think this needs/deserves a note in Migration guide of ROS Noetic, doesn't it? Is there a way for packages to choose which version they want, which is reliable both during build time and run time?

Build failures like the following are surprising and hard to debug: https://build.ros.org/job/Ndev__robot_body_filter__ubuntu_focal_amd64/1/console

```
22:15:07 [ 21%] Linking CXX executable /tmp/ws/devel_isolated/robot_body_filter/lib/robot_body_filter/test_tf2_eigen
22:15:11 /usr/bin/ld: /tmp/ws/devel_isolated/robot_body_filter/lib/librobot_body_filter_utils.so: undefined reference to `fcl::OBB::operator+(fcl::OBB const&) const'
22:15:11 /usr/bin/ld: /tmp/ws/devel_isolated/robot_body_filter/lib/librobot_body_filter_utils.so: undefined reference to `fcl::OBB::overlap(fcl::OBB const&) const'
22:15:11 /usr/bin/ld: /tmp/ws/devel_isolated/robot_body_filter/lib/librobot_body_filter_utils.so: undefined reference to `fcl::OBB::contain(fcl::Vec3fX<fcl::details::Vec3Data<double> > const&) const'
22:15:11 collect2: error: ld returned 1 exit status
```

For example, I was unable to recreate this situation on my computer. It seems that CMake chose FCL 0.6.1 (from the logs), then built the library using 0.5 headers (probably because I include only a header that's in 0.5), and the ran the linker with the 0.6.1 library.

It took me about an hour until I figured out what happened. Documenting this and giving some suggestions could save some other people time upgrading their packages to Noetic.

**Comment by traversaro** [comment]
I am not sure if this is the best place (i.e. the place where you can find the most interest people in this). The issue of two different versions of fcl being released in apt Debian/Ubuntu repo and in ROS build farm seems to be more a problem of ROS distribution rather then an upstream problem of fcl (that can be consume in several ways, Debian binaries, ROS Debian binaries, as bazel external, via vcpkg, via conda-forge, etc etc). 

Some related issue on rosdistro seem to be https://github.com/ros/rosdistro/pull/26706 and https://github.com/ros/rosdistro/issues/26527, perhaps it could make sense to drop a comment in https://github.com/ros/rosdistro/issues/26527 ?

**Comment by peci1** [comment]
Thanks for the redirect, I did not know exactly where to report this. So I'm closing this issue here and discussion will (hopefully) follow in https://github.com/ros/rosdistro/pull/26706 .

**Comment by traversaro** [comment]
Related issues, but on ROS2:
* https://github.com/ros/rosdistro/pull/29614
* https://github.com/flexible-collision-library/fcl/issues/537
