### ISSUE TITLE
Segfault in `hierarchy_tree-inl.h`

### ISSUE THREAD

**Issue by JStech** [flexible-collision-library/fcl#535]
I'm hitting a segfault at [L365 of `hierarchy_tree-inl.h`](https://github.com/flexible-collision-library/fcl/blob/7980061604ca8df4872a1c5139074b780d82fe08/include/fcl/broadphase/detail/hierarchy_tree-inl.h#L365), apparently because the condition in L356 is never met and so `min_it1` and `min_it2` are never initialized. This is happening within MoveIt, in [`collision_detection::FCLObject::registerTo`](https://github.com/ros-planning/moveit/blob/9bc4b8960a0cbdc25690dd39dc008a4b9e1873cc/moveit_core/collision_detection_fcl/src/collision_common.cpp#L945).

It's definitely possible that we're feeding FCL bad inputs here, although this is happening deep enough in the MoveIt code that I'm unsure about everything. It'd be helpful if this error were caught, though, and reported with an informative error message.

**Comment by JStech** [comment]
We are in fact feeding in bad inputs. There are several collision objects with lots of NaNs in them (in their transforms and AABBs) that MoveIt is passing into the collision manager `registerObjects` function. I'll close this issue.

**Comment by tylerjw** [comment]
This issue looks related: https://github.com/flexible-collision-library/fcl/issues/521
