### ISSUE TITLE
Error in matrix_3f.h

### ISSUE THREAD

**Issue by SchneiderDaniel** [flexible-collision-library/fcl#55]
The function isIdentity() in matrix_3f.h returns a false value:
Current:
  inline bool isIdentity () const
  {
    return
      data (0,0) == 1 && data (0,1) == 0 && data (0,2) == 0 &&
      data (0,0) == 0 && data (0,1) == 1 && data (0,2) == 0 &&
      data (0,0) == 0 && data (0,1) == 0 && data (0,2) == 1;
  }
 Should be:
  inline bool isIdentity () const
  {
    return
      data (0,0) == 1 && data (0,1) == 0 && data (0,2) == 0 &&
      data (1,0) == 0 && data (1,1) == 1 && data (1,2) == 0 &&
      data (2,0) == 0 && data (2,1) == 0 && data (2,2) == 1;
  }

Daniel

**Comment by mamoll** [comment]
Fixed in ea6ccd8
