### ISSUE TITLE
Warning: distance function between node type 2 and node type 2 is not supported

### ISSUE THREAD

**Issue by WangZP10969** [flexible-collision-library/fcl#554]
I am using the BVH model to calculate the closest distance between triangles, using the default fcl::DistanceRequestd and fcl::DistanceResultd, and then calling fcl::distance

```
fcl::DistanceRequestd DistanceRequest(false, false);
fcl::DistanceResultd DistanceResult;
fcl::distance(CollisionObject1.get(), CollisionObject2.get(), DistanceRequest, DistanceResult);
```

Console output warning
```
Warning: distance function between node type 2 and node type 2 is not supported
```

What could cause this?

**Comment by jmirabel** [comment]
To resolve such kind of issue, you can have a look at the source code.
Maybe your two BVH do not use the same type of bounding volumes.

**Comment by WangZP10969** [comment]
@jmirabel 
Thank you very much for your suggestions. I found that BV_AABB and GEOM_BOX were calculated during my distance calculation. 
That is to say, for collision detection, these two types are possible, but for distance detection, I need to convert GEOM_BOX to BV_AABB?
