### ISSUE TITLE
What does GST_INDEP mean?

### ISSUE THREAD

**Issue by QUIlToT** [flexible-collision-library/fcl#593]
Hi!

Are there some instructions on the narrow phase solver `GST_INDEP` to know the difference between `GST_INDEP`and `GST_LIBCCD`?

Help would be much appreciated!

**Comment by SeanCurtis-TRI** [comment]
The "independent" solver (`GST_INDEP`) looks to me like a tentative effort and writing an FCL-only solver (one that doesn't depend on libccd). Our early tinkering with it left us feeling like the `GST_LIBCCD` solver was more reliable. I don't know if that's definitively true, but I can say that based on that belief, all of the recent efforts to provide solver fixes have been solely focused on `GST_LIBCCD`.

Feel free to try `GST_INDEP`, if you find circumstances where it clearly provides superior results, please let us know.

**Comment by yckm** [comment]
[1645774_smaple.json](https://github.com/flexible-collision-library/fcl/files/13405461/1645774_smaple.json)
1645774_smaple.json文件是我对fcl模型采样后的点云数据.
我在计算机械臂到外部环境距离的时候,使用fcl::GJKSolverType::GST_LIBCCD;发现最近点并不在建立的圆柱体表面,而当我将类型更换为fcl::GJKSolverType::GST_INDEP后,效果非常好.
这是使用fcl::GJKSolverType::GST_INDEP的结果(正确):
![image](https://github.com/flexible-collision-library/fcl/assets/98254947/231688fb-2102-4dbd-953b-c79b3097004f)
这是使用 fcl::GJKSolverType::GST_LIBCCD的结果(错误):
![image](https://github.com/flexible-collision-library/fcl/assets/98254947/d98e34c2-0f6c-4ee7-8c2f-a950c3e713f5)
