### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by afabri** [flexible-collision-library/fcl#7]
There are doxygen style comments in the header files.
Could you add a Doxyfile, for example the one that was used to produce 
http://gamma.cs.unc.edu/FCL/fcl_docs/webpage/generated/annotated.html

**Comment by jslee02** [comment]
Doxyfile was added by #174. It's not the one that was used to generate [the original documentation](http://gamma.cs.unc.edu/FCL/fcl_docs/webpage/generated/annotated.html), but we could keep updating the new Doxyfile if needed.
