### ISSUE TITLE
OSX test failure: test_fcl_geometric_shapes with libccd

### ISSUE THREAD

**Issue by scpeters** [flexible-collision-library/fcl#71]
I'm seeing some failures of `test_fcl_geometric_shapes` on OS X ([details here](https://gist.github.com/scpeters/3d1d2afc7ecb434b9b84)). Many of the test failures reference libccd. I'm using libccd 2.0 from homebrew.

**Comment by jslee02** [comment]
This should be addressed by #52.

**Comment by jslee02** [comment]
I believe this is resolved as the tests are being passed on travis. Please reopen if it's not.
