### ISSUE TITLE
Consistent directionality of normals for mesh-mesh collision detection

### ISSUE THREAD

**Issue by aleeper** [flexible-collision-library/fcl#8]
I sent some emails about this a long time ago, but I figured it's worth documenting with a ticket :)

In any case, is there (supposed to be) a standard that says, given a contact result between object #1 and object #2, whether the provided normal points from 1 to 2, or from 2 to 1?

In MoveIt!, it seems that robot-robot collision results are ambiguous as to the direction of the normal. This may be a problem in how MoveIt! interprets the FCL result, or it might be in FCL. For example, if I move the right arm into collision with the left arm, it seems to be somewhat non-deterministic whether the reported contact normal points from link 1 to link 2, or from link 2 to link 1.

**Comment by jslee02** [comment]
I found that 
* [the provided normal direction of FCL should points from 1 to 2](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/collision_data.h#L80)
* mesh-mesh normal returns normal in that way
* shape-[shape/mesh] returns reversed normal direction, which points from 2 to 1

Pull request #61 should fix this inconsistency.

What I'm wondering is whether mesh-mesh collision returns inconsistent normal directions as you described. Could you clarify if the inconsistent normal direction happened for mesh-mesh or shape-[mesh/shape]?

**Comment by jslee02** [comment]
I believe this is resolved by #61. Please let me know or reopen this issue if it's not.
