### ISSUE TITLE
FCL logo

### ISSUE THREAD

**Issue by jslee02** [flexible-collision-library/fcl#82]
As FCL still doesn't have a logo, I would like to propose one:

<img src="https://cloud.githubusercontent.com/assets/4038467/10743178/d546df8a-7c07-11e5-81cb-c01f64d54cbd.png" alt="FCL logo" width="250" />

The three letters, "FCL", are laid on each invisible layers in a cube. "C" letter is colored by red to emphasize **collision** and to indicate it is colliding with other two letters.

**Comment by isucan** [comment]
This looks really cool! I like it!

**Comment by jslee02** [comment]
Thanks @isucan ! I would like to use this logo for [`flexible-collision-library` organization](https://github.com/flexible-collision-library) as a first step if others also agree. :smile:

**Comment by karenliu** [comment]
It looks awesome!

**Comment by jslee02** [comment]
Let's take this as the first logo of FCL. I'm closing this issue, but feedback is welcome anytime!
