### ISSUE TITLE
Cone transformations

### ISSUE THREAD

**Issue by cyberguijarro** [flexible-collision-library/fcl#83]
Hi,

when positioning a Cone shape at (0,0,0), is the cone's base or apex at (0,0,0)?
when rotating a Cone shape, does it rotate around the base or the apex?

Thanks!

**Comment by jslee02** [comment]
[According to the COM computation](https://github.com/flexible-collision-library/fcl/blob/master/include/fcl/shape/geometric_shapes.h#L261), it seems the origin of a cone is at the mid point of the cone's base and apex (note that a cone's COM is at the 1/4 height from the base). So (0, 0, 0) refers to the origin, and the Cone rotates around the origin as well.

**Comment by cyberguijarro** [comment]
Seems correct. Thanks a lot jslee02.

**Comment by jslee02** [comment]
Your welcome. I'm closing this issue. Please reopen if needed.
